server:
  port: 8888

# 应用名称
spring:
  application:
    name: spring-boot-sqlite
  datasource:
    # url最容易出错，如果使用相对于项目的相对地址，那么填入 jdbc:sqlite::resource:sqlit数据库所在位置
    # 注：
    # :resource: 指向项目的 resources 路径（resource前后两个 `:` 不能省略）
    url: jdbc:sqlite::resource:db/user.sqlite
    driver-class-name: org.sqlite.JDBC
    # username: 选用 sqlite 数据库不需要配置此项
    # password: 选用 sqlite 数据库不需要配置此项
  sql:
    init:
      # DDL建表语句
      schema-locations: classpath:db/schema.sql
      # DML添加数据
      data-locations: classpath:db/data.sql
      mode: always
      continue-on-error: true

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.joinhealth.springbootsqlite.model

